name: Dependency Review
on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sbt/setup-sbt@v1
      - uses: scalacenter/sbt-dependency-submission@v2
      - uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
      - name: Log vulnerable changes
        # make sure this step runs even if the previous failed
        if: ${{ failure() && steps.review.conclusion == 'failure' }}
        shell: bash
        env:
          VULNERABLE_CHANGES: ${{ steps.review.outputs.vulnerable-changes }}
        run: |
          echo "$VULNERABLE_CHANGES" | jq
  
