name: Dependency Review
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sbt/setup-sbt@v1
      - uses: scalacenter/sbt-dependency-submission@v2
      - uses: actions/dependency-review-action@v4
