name: Dependency Review
on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sbt/setup-sbt@v1
      - uses: scalacenter/sbt-dependency-submission@v2
      - uses: actions/dependency-review-action@v4
        id: review
        with:
          comment-summary-in-pr: always
      - name: Log vulnerable changes
        if: always()
        shell: bash
        env:
          VULNERABLE_CHANGES: ${{ steps.review.outputs.vulnerable-changes }}
        run: |
          echo "$VULNERABLE_CHANGES" | jq
      - name: Log all dependency changes
        if: always()
        shell: bash
        env:
          DEP_CHANGES: ${{ steps.review.outputs.dependency-changes }}
        run: |
          echo "$DEP_CHANGES" | jq
  
